#!/usr/bin/env bash
# generate-wal-theme.sh
# Reads ~/.cache/wal/colors and writes ~/.config/zed/themes/wal-system.json
# Run this after pywal regenerates your palette (e.g. add it to your wal hook).
#
# Color role mapping (GitHub Dark skeleton, UI replaced by wal palette):
#   color0  → darkest surface / editor background
#   color1  → keywords, operators, errors, constructors
#   color2  → success, created, tags, json keys
#   color3  → strings, enum, types, warnings
#   color4  → accent (blue): links, constants, booleans, numbers, labels
#   color5  → functions, methods
#   color6  → muted accents, info, modified
#   color7  → foreground / primary text
#   color8  → slightly lighter surface (active line, panels)
#   color15 → bright foreground (if available, else color7)
#
# Syntax colors (keywords, functions, strings, etc.) are taken directly from
# the GitHub Dark theme — only UI chrome colors adapt to the wal palette.

set -euo pipefail

WAL_COLORS="${HOME}/.cache/wal/colors"
OUT="${HOME}/.config/zed/themes/wal-system.json"

if [[ ! -f "$WAL_COLORS" ]]; then
  echo "Error: $WAL_COLORS not found. Run pywal first." >&2
  exit 1
fi

# Read the 16 colors into an array (strip the leading #)
mapfile -t RAW < "$WAL_COLORS"

# Helper: strip leading #
strip() { echo "${1#\#}"; }

# All 16 colors as plain rrggbb hex strings
C=()
for raw in "${RAW[@]}"; do
  C+=( "$(strip "$raw")" )
done

# Pad to 16 in case pywal only gives 8
while (( ${#C[@]} < 16 )); do
  C+=( "${C[7]}" )
done

# ── Arithmetic helpers ────────────────────────────────────────────────────────

# clamp $1 to [0,255]
clamp() {
  local v=$1
  (( v < 0   )) && v=0
  (( v > 255 )) && v=255
  echo $v
}

# adjust_channel  hex2char  delta  → 2-char hex string
adjust_channel() {
  local ch=$1 delta=$2
  local val=$(( 16#$ch + delta ))
  val=$(clamp $val)
  printf '%02x' $val
}

# lighten/darken a rrggbb hex by $delta per channel
adjust_color() {
  local hex=$1 delta=$2
  local rr="${hex:0:2}" gg="${hex:2:2}" bb="${hex:4:2}"
  echo "$(adjust_channel "$rr" $delta)$(adjust_channel "$gg" $delta)$(adjust_channel "$bb" $delta)"
}

# append ff alpha suffix for Zed
zc() { echo "#${1}ff"; }
# with custom alpha (00–ff)
zca() { echo "#${1}${2}"; }

# ── Derive palette roles ──────────────────────────────────────────────────────

BG="${C[0]}"            # darkest bg
FG="${C[7]}"            # primary text
BG_BRIGHT="${C[15]}"    # brightest fg (used for bright text)

# Surface layers (slightly lighter than BG)
SURFACE=$(adjust_color "$BG" 6)        # panel / status bar / tab bar
ACTIVE_LINE=$(adjust_color "$BG" 10)   # active line highlight
ELEVATED=$(adjust_color "$BG" -3)      # elevated surface (deepest panels)

# Border (subtle, between bg and surface)
BORDER=$(adjust_color "$BG" 25)
BORDER_MUTED=$(adjust_color "$BG" 18)

# Muted text (line numbers, hints, placeholders)
MUTED="${C[8]}"

# Accent colors
ACCENT="${C[4]}"        # primary accent: links, focus borders, cursor
ACCENT2="${C[5]}"       # secondary: functions (kept from GH Dark syntax)
KEYWORD="${C[1]}"       # keywords → red family
SUCCESS="${C[2]}"       # green family
WARN="${C[3]}"          # yellow / warm
INFO="${C[6]}"          # cyan / info

# Selection background (~26% opacity on accent)
SEL_BG=$(adjust_color "$ACCENT" -40)

# ── Syntax colors (kept from GitHub Dark — don't touch these) ─────────────────
# These are the unchanged GitHub Dark syntax token colors.
# The only thing that changes is the UI chrome above.
SYN_KEYWORD="#ff7b72"
SYN_FUNC="#d2a8ff"
SYN_CONST="#79c0ff"
SYN_STRING="#a5d6ff"
SYN_STRING_WARM="#a5d6ff"
SYN_ENUM="#ffa657"
SYN_TAG="#7ee787"
SYN_COMMENT="#9198a1"
SYN_PROP="#f0f6fc"
SYN_FG="#f0f6fc"

# ── Write JSON ────────────────────────────────────────────────────────────────

mkdir -p "$(dirname "$OUT")"

cat > "$OUT" << ENDJSON
{
  "\$schema": "https://zed.dev/schema/themes/v0.1.0.json",
  "name": "Wal System Theme",
  "author": "Generated by generate-wal-theme.sh",
  "themes": [
    {
      "appearance": "dark",
      "name": "Wal System Theme",
      "style": {
        "accents": [
          "$(zc "$ACCENT")",
          "$(zc "$SUCCESS")",
          "$(zc "$WARN")",
          "$(zc "$KEYWORD")",
          "$(zc "$ACCENT2")",
          "$(zc "$INFO")"
        ],
        "background.appearance": "opaque",
        "background":                        "$(zc "$BG")",
        "border":                            "$(zc "$BORDER")",
        "border.disabled":                   "$(zca "$MUTED" "1a")",
        "border.focused":                    "$(zc "$ACCENT")",
        "border.selected":                   "$(zc "$ACCENT")",
        "border.transparent":                "#00000000",
        "border.variant":                    "$(zca "$BORDER" "b3")",
        "conflict":                          "$(zc "$WARN")",
        "conflict.background":               "$(zca "$WARN" "1a")",
        "conflict.border":                   "$(zca "$WARN" "66")",
        "created":                           "$(zc "$SUCCESS")",
        "created.background":                "$(zca "$SUCCESS" "26")",
        "created.border":                    "$(zca "$SUCCESS" "66")",
        "deleted":                           "$(zc "$KEYWORD")",
        "deleted.background":                "$(zca "$KEYWORD" "1a")",
        "deleted.border":                    "$(zca "$KEYWORD" "66")",
        "drop_target.background":            "$(zca "$ACCENT" "1a")",
        "editor.active_line.background":     "$(zc "$ACTIVE_LINE")",
        "editor.active_line_number":         "$(zc "$FG")",
        "editor.active_wrap_guide":          "$(zca "$BORDER" "b3")",
        "editor.background":                 "$(zc "$BG")",
        "editor.document_highlight.read_background": "$(zca "$ACCENT" "4d")",
        "editor.document_highlight.write_background": "$(zca "$ACCENT" "33")",
        "editor.foreground":                 "$(zc "$FG")",
        "editor.gutter.background":          "$(zc "$BG")",
        "editor.highlighted_line.background":"$(zca "$MUTED" "33")",
        "editor.invisible":                  "$(zc "$MUTED")",
        "editor.line_number":                "$(zc "$MUTED")",
        "editor.subheader.background":       "$(zc "$ACTIVE_LINE")",
        "editor.wrap_guide":                 "$(zca "$BORDER" "b3")",
        "element.active":                    "$(zca "$MUTED" "33")",
        "element.background":                "$(zca "$MUTED" "33")",
        "element.disabled":                  "$(zc "$SURFACE")",
        "element.hover":                     "$(zca "$MUTED" "33")",
        "element.selected":                  "$(zca "$MUTED" "33")",
        "elevated_surface.background":       "$(zc "$ELEVATED")",
        "error":                             "$(zc "$KEYWORD")",
        "error.background":                  "$(zc "$ACTIVE_LINE")",
        "error.border":                      "$(zca "$BORDER" "b3")",
        "ghost_element.active":              "$(zca "$MUTED" "33")",
        "ghost_element.background":          "#00000000",
        "ghost_element.disabled":            "$(zc "$SURFACE")",
        "ghost_element.hover":               "$(zca "$MUTED" "33")",
        "ghost_element.selected":            "$(zca "$MUTED" "33")",
        "hidden":                            "$(zc "$MUTED")",
        "hidden.background":                 "$(zc "$SURFACE")",
        "hidden.border":                     "$(zca "$MUTED" "1a")",
        "hint":                              "$(zc "$MUTED")",
        "hint.background":                   "$(zc "$ACTIVE_LINE")",
        "hint.border":                       "$(zca "$BORDER" "b3")",
        "icon":                              "$(zc "$FG")",
        "icon.background":                   "$(zc "$BG")",
        "icon.border":                       "$(zc "$BORDER")",
        "icon.accent":                       "$(zc "$ACCENT")",
        "icon.muted":                        "$(zc "$MUTED")",
        "icon.disabled":                     "$(zc "$MUTED")",
        "ignored":                           "$(zc "$MUTED")",
        "ignored.background":                "$(zc "$SURFACE")",
        "ignored.border":                    "$(zca "$MUTED" "1a")",
        "info":                              "$(zc "$INFO")",
        "info.background":                   "$(zc "$ACTIVE_LINE")",
        "info.border":                       "$(zca "$BORDER" "b3")",
        "link_text.hover":                   "$(zc "$ACCENT")",
        "modified":                          "$(zc "$WARN")",
        "modified.background":               "$(zca "$WARN" "26")",
        "modified.border":                   "$(zca "$WARN" "66")",
        "pane.focused_border":               "$(zc "$BORDER")",
        "panel.background":                  "$(zc "$ELEVATED")",
        "panel.focused_border":              "$(zc "$BORDER")",
        "predictive":                        "$(zc "$MUTED")",
        "predictive.background":             "$(zca "$MUTED" "33")",
        "predictive.border":                 "$(zca "$BORDER" "b3")",
        "renamed":                           "$(zc "$SUCCESS")",
        "renamed.background":                "$(zca "$SUCCESS" "26")",
        "renamed.border":                    "$(zca "$SUCCESS" "66")",
        "scrollbar.thumb.border":            "#00000000",
        "scrollbar.thumb.hover_background":  "$(zca "$MUTED" "66")",
        "scrollbar.thumb.background":        "$(zca "$MUTED" "4d")",
        "scrollbar.track.background":        "#00000000",
        "scrollbar.track.border":            "#00000000",
        "search.match_background":           "$(zca "$WARN" "4d")",
        "status_bar.background":             "$(zc "$ELEVATED")",
        "success":                           "$(zc "$SUCCESS")",
        "success.background":                "$(zca "$SUCCESS" "26")",
        "success.border":                    "$(zca "$SUCCESS" "66")",
        "surface.background":                "$(zc "$ELEVATED")",
        "tab.active_background":             "$(zc "$BG")",
        "tab.inactive_background":           "$(zc "$ELEVATED")",
        "tab_bar.background":                "$(zc "$ELEVATED")",
        "terminal.ansi.black":               "$(zc "${C[0]}")",
        "terminal.ansi.bright_black":        "$(zc "${C[8]}")",
        "terminal.ansi.dim_black":           "$(zc "${C[0]}")",
        "terminal.ansi.blue":                "$(zc "${C[4]}")",
        "terminal.ansi.bright_blue":         "$(zc "${C[12]}")",
        "terminal.ansi.dim_blue":            "$(zc "${C[4]}")",
        "terminal.ansi.cyan":                "$(zc "${C[6]}")",
        "terminal.ansi.bright_cyan":         "$(zc "${C[14]}")",
        "terminal.ansi.dim_cyan":            "$(zc "${C[6]}")",
        "terminal.ansi.green":               "$(zc "${C[2]}")",
        "terminal.ansi.bright_green":        "$(zc "${C[10]}")",
        "terminal.ansi.dim_green":           "$(zc "${C[2]}")",
        "terminal.ansi.magenta":             "$(zc "${C[5]}")",
        "terminal.ansi.bright_magenta":      "$(zc "${C[13]}")",
        "terminal.ansi.dim_magenta":         "$(zc "${C[5]}")",
        "terminal.ansi.red":                 "$(zc "${C[1]}")",
        "terminal.ansi.bright_red":          "$(zc "${C[9]}")",
        "terminal.ansi.dim_red":             "$(zc "${C[1]}")",
        "terminal.ansi.white":               "$(zc "${C[7]}")",
        "terminal.ansi.bright_white":        "$(zc "${C[15]}")",
        "terminal.ansi.dim_white":           "$(zc "${C[7]}")",
        "terminal.ansi.yellow":              "$(zc "${C[3]}")",
        "terminal.ansi.bright_yellow":       "$(zc "${C[11]}")",
        "terminal.ansi.dim_yellow":          "$(zc "${C[3]}")",
        "terminal.background":               "$(zc "$ELEVATED")",
        "terminal.bright_foreground":        "$(zc "$BG_BRIGHT")",
        "terminal.dim_foreground":           "$(zc "$MUTED")",
        "terminal.foreground":               "$(zc "$FG")",
        "text":                              "$(zc "$FG")",
        "text.accent":                       "$(zc "$ACCENT")",
        "text.disabled":                     "$(zc "$MUTED")",
        "text.muted":                        "$(zc "$FG")",
        "text.placeholder":                  "$(zc "$MUTED")",
        "title_bar.background":              "$(zc "$ELEVATED")",
        "toolbar.background":                "$(zc "$BG")",
        "unreachable":                       "$(zc "$MUTED")",
        "unreachable.background":            "$(zc "$SURFACE")",
        "unreachable.border":                "$(zca "$MUTED" "1a")",
        "vim.normal.foreground":             "#ffffffff",
        "vim.normal.background":             "$(zc "$MUTED")",
        "vim.helix_normal.foreground":       "#ffffffff",
        "vim.helix_normal.background":       "$(zc "$MUTED")",
        "vim.visual.foreground":             "#ffffffff",
        "vim.visual.background":             "$(zc "$ACCENT")",
        "vim.helix_select.foreground":       "#ffffffff",
        "vim.helix_select.background":       "$(zc "$ACCENT")",
        "vim.insert.foreground":             "#ffffffff",
        "vim.insert.background":             "$(zc "$SUCCESS")",
        "vim.visual_line.foreground":        "#ffffffff",
        "vim.visual_line.background":        "$(zc "$ACCENT")",
        "vim.visual_block.foreground":       "#ffffffff",
        "vim.visual_block.background":       "$(zc "$ACCENT2")",
        "vim.replace.foreground":            "#ffffffff",
        "vim.replace.background":            "$(zc "$KEYWORD")",
        "warning":                           "$(zc "$WARN")",
        "warning.background":                "$(zc "$ACTIVE_LINE")",
        "warning.border":                    "$(zca "$BORDER" "b3")",
        "players": [
          { "cursor": "$(zc "$ACCENT")",  "background": "$(zc "$ACCENT")",  "selection": "$(zca "$ACCENT"  "66")" },
          { "cursor": "$(zc "$SUCCESS")", "background": "$(zc "$SUCCESS")", "selection": "$(zca "$SUCCESS" "66")" },
          { "cursor": "$(zc "$WARN")",    "background": "$(zc "$WARN")",    "selection": "$(zca "$WARN"    "66")" },
          { "cursor": "$(zc "$KEYWORD")", "background": "$(zc "$KEYWORD")", "selection": "$(zca "$KEYWORD" "66")" },
          { "cursor": "$(zc "$ACCENT2")", "background": "$(zc "$ACCENT2")", "selection": "$(zca "$ACCENT2" "66")" },
          { "cursor": "$(zc "$INFO")",    "background": "$(zc "$INFO")",    "selection": "$(zca "$INFO"    "66")" }
        ],
        "syntax": {
          "attribute":                  { "color": "${SYN_CONST}ff",    "font_style": null, "font_weight": null },
          "boolean":                    { "color": "${SYN_CONST}ff",    "font_style": null, "font_weight": null },
          "comment":                    { "color": "${SYN_COMMENT}ff",  "font_style": null, "font_weight": null },
          "comment.doc":                { "color": "${SYN_COMMENT}ff",  "font_style": null, "font_weight": null },
          "constant":                   { "color": "${SYN_CONST}ff",    "font_style": null, "font_weight": null },
          "constructor":                { "color": "${SYN_KEYWORD}ff",  "font_style": null, "font_weight": null },
          "embedded":                   { "color": "${SYN_KEYWORD}ff",  "font_style": null, "font_weight": null },
          "emphasis":                   { "color": null,                "font_style": "italic", "font_weight": null },
          "emphasis.strong":            { "color": null,                "font_style": null, "font_weight": 700 },
          "enum":                       { "color": "${SYN_ENUM}ff",     "font_style": null, "font_weight": null },
          "function":                   { "color": "${SYN_FUNC}ff",     "font_style": null, "font_weight": null },
          "function.method":            { "color": "${SYN_FUNC}ff",     "font_style": null, "font_weight": null },
          "function.special.definition":{ "color": "${SYN_FUNC}ff",     "font_style": null, "font_weight": null },
          "hint":                       { "color": "${SYN_COMMENT}ff",  "font_style": null, "font_weight": 700 },
          "keyword":                    { "color": "${SYN_KEYWORD}ff",  "font_style": null, "font_weight": null },
          "keyword.operator":           { "color": "${SYN_KEYWORD}ff",  "font_style": null, "font_weight": null },
          "label":                      { "color": "${SYN_CONST}ff",    "font_style": null, "font_weight": null },
          "link_text":                  { "color": "${SYN_STRING}ff",   "font_style": "italic", "font_weight": null },
          "link_uri":                   { "color": "${SYN_CONST}ff",    "font_style": null, "font_weight": null },
          "number":                     { "color": "${SYN_CONST}ff",    "font_style": null, "font_weight": null },
          "operator":                   { "color": "${SYN_KEYWORD}ff",  "font_style": null, "font_weight": null },
          "predictive":                 { "color": "${SYN_COMMENT}ff",  "font_style": "italic", "font_weight": null },
          "preproc":                    { "color": "${SYN_KEYWORD}ff",  "font_style": null, "font_weight": null },
          "primary":                    { "color": "${SYN_FG}ff",       "font_style": null, "font_weight": null },
          "property":                   { "color": "${SYN_PROP}ff",     "font_style": null, "font_weight": null },
          "property.json_key":          { "color": "${SYN_TAG}ff",      "font_style": null, "font_weight": null },
          "punctuation":                { "color": "${SYN_KEYWORD}ff",  "font_style": null, "font_weight": null },
          "punctuation.bracket":        { "color": "${SYN_FG}ff",       "font_style": null, "font_weight": null },
          "punctuation.delimiter":      { "color": "${SYN_FG}ff",       "font_style": null, "font_weight": null },
          "punctuation.delimiter.jsx":  { "color": "${SYN_KEYWORD}ff",  "font_style": null, "font_weight": null },
          "punctuation.list_marker":    { "color": "${SYN_ENUM}ff",     "font_style": null, "font_weight": null },
          "punctuation.special":        { "color": "${SYN_KEYWORD}ff",  "font_style": null, "font_weight": null },
          "string":                     { "color": "${SYN_STRING}ff",   "font_style": null, "font_weight": null },
          "string.escape":              { "color": "${SYN_KEYWORD}ff",  "font_style": null, "font_weight": null },
          "string.regex":               { "color": "${SYN_STRING}ff",   "font_style": null, "font_weight": null },
          "string.special":             { "color": "${SYN_CONST}ff",    "font_style": null, "font_weight": null },
          "string.special.symbol":      { "color": "${SYN_CONST}ff",    "font_style": null, "font_weight": null },
          "tag":                        { "color": "${SYN_TAG}ff",      "font_style": null, "font_weight": null },
          "text.literal":               { "color": "${SYN_CONST}ff",    "font_style": null, "font_weight": null },
          "title":                      { "color": "${SYN_CONST}ff",    "font_style": null, "font_weight": 700 },
          "type":                       { "color": "${SYN_ENUM}ff",     "font_style": null, "font_weight": null },
          "type.builtin":               { "color": "${SYN_CONST}ff",    "font_style": null, "font_weight": null },
          "variable":                   { "color": "${SYN_FG}ff",       "font_style": null, "font_weight": null },
          "variable.builtin":           { "color": "${SYN_CONST}ff",    "font_style": null, "font_weight": null },
          "variable.parameter":         { "color": "${SYN_ENUM}ff",     "font_style": null, "font_weight": null },
          "variable.special":           { "color": "${SYN_CONST}ff",    "font_style": null, "font_weight": null },
          "variant":                    { "color": "${SYN_ENUM}ff",     "font_style": null, "font_weight": null }
        }
      }
    }
  ]
}
ENDJSON

echo "Written: $OUT"
